### ISSUE TITLE
Use with geocoder or searchkick ?

### ISSUE THREAD

**Issue by bricesanchez** [ionia-corporation/active_force#97]
Hello !

Do you know if there is a way to use your gem with the `geocoder` or `searchkick` gem ?

I'm trying to find `Account` records near to a latitude/longitude.

Do you have any idea to help me ?

Thanks !

**Comment by olvap** [comment]
I didn't try yet. but let me check it. The short answer is no for now.

I think the geocoder has a function to work with sqlite that don't use any of the sql function to calculate distances. May be you could try to set sqlite on geocoder and try it out.

Please, let me know if you fond something.

**Comment by bricesanchez** [comment]
I found this : http://www.salesforce.com/us/developer/docs/soql_sosl/Content/sforce_api_calls_soql_geolocate.htm

It could be my answer, i test it. :)

**Comment by bricesanchez** [comment]
It works with geolocation fields and salesforce DISTANCE query.

Thanks for your help :)
