### ISSUE TITLE
Can't access to Restforce::Mash

### ISSUE THREAD

**Issue by bricesanchez** [ionia-corporation/active_force#99]
Hello all !

I don't know why but i'm not able to access to latitude and longitude include in location field :

```ruby
undefined method `latitude' for "#<Restforce::Mash latitude=43.0082399 longitude=-88.0568406>":String

Extracted source (around line #13):
    if @accounts
      @hash = Gmaps4rails.build_markers(@accounts) do |account, marker|
        raise account.location.latitude.inspect
        # marker.lat account.location.latitude
        # marker.lng account.location.longitude
        marker.infowindow account.name
```

Could you help me to understand why ?

**Comment by bricesanchez** [comment]
`In API versions below 30.0, SOAP calls return compound geolocation field values as strings, instead of a structured data type, for backwards compatibility. The string value format is:`

But my Restforce `config.api_version` is '33.0'

**Comment by olvap** [comment]
If the location method is returning a Restforce::Mash object, you cant ask for 'location' method, unless some how you can run the build mehotd on the location response.

~~~ ruby
location = ActiveForce::SObject.build account.location
location.latitud
~~~
https://github.com/ionia-corporation/active_force/blob/master/lib/active_force/sobject.rb#L52

or something like this...

~~~ ruby
account.location['latitude']
~~~

The build method is call on the belongs_to assoc (and on new instances). If you need it on the geolocation field, we'll should have to patch it.

Let me know if you have any doubt.

**Comment by bricesanchez** [comment]
Sorry, i'm not sure to understand.

If i test your first example, it respond this : 
```ruby
undefined method `each' for "#<Restforce::Mash latitude=43.0082399 longitude=-88.0568406>":String

Extracted source (around line #13):         
    if @accounts
      @hash = Gmaps4rails.build_markers(@accounts) do |account, marker|
        location = ActiveForce::SObject.build account.location
        # marker.lat account.location.latitude
        # marker.lng account.location.longitude
        marker.infowindow account.name
```

If i test your second example, it respond this :
```ruby
latitude

Extracted source (around line #13):
    if @accounts
      @hash = Gmaps4rails.build_markers(@accounts) do |account, marker|
        raise account.location['latitude']
        # marker.lat account.location.latitude
        # marker.lng account.location.longitude
        marker.infowindow account.name
```

How could we patch the geolocation field ?

**Comment by bricesanchez** [comment]
I have the same problem with other compound fields, the problem is may be not with geolocation fields ?

**Comment by bricesanchez** [comment]
Do you have any other clue for my issue ?
